export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const UPDATE_USER_IMAGE_START = "UPDATE_USER_IMAGE_START";
export const UPDATE_USER_IMAGE_SUCCESS = "UPDATE_USER_IMAGE_SUCCESS";
export const UPDATE_USER_IMAGE_FAIL = "UPDATE_USER_IMAGE_FAIL";
export const UPDATE_USER_INFO_START = "UPDATE_USER_INFO_START";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_FAIL = "UPDATE_USER_INFO_FAIL";
export const RESET_UPDATE_USER_SUCCESS = "RESET_UPDATE_USER_SUCCESS";
export const FOLLOW_START = "FOLLOW_START";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
export const FOLLOW_FAIL = "FOLLOW_FAIL";
export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";
export const RESET_USER = "RESET_USER";

export const GET_FEED_POSTS_START = "GET_FEED_POSTS_START";
export const GET_FEED_POSTS_SUCCESS = "GET_FEED_POSTS_SUCCESS";
export const GET_FEED_POSTS_FAIL = "GET_FEED_POSTS_FAIL";
export const ADD_FEED_POST_START = "ADD_FEED_POST_START";
export const ADD_FEED_POST_SUCCESS = "ADD_FEED_POST_SUCCESS";
export const ADD_FEED_POST_FAIL = "ADD_FEED_POST_FAIL";
// export const DELETE_FEED_POST_START = "DELETE_FEED_POST_START";
// export const DELETE_FEED_POST_FAIL = "DELETE_FEED_POST_FAIL";
export const DELETE_FEED_POST_SUCCESS = "DELETE_FEED_POST_SUCCESS";
export const CLEAR_FEED_ERROR = "CLEAR_FEED_ERROR";
export const RESET_FEED = "RESET_FEED";

export const GET_GUEST_BOOK_MESSAGES_START = "GET_GUEST_BOOK_MESSAGES_START";
export const GET_GUEST_BOOK_MESSAGES_SUCCESS =
  "GET_GUEST_BOOK_MESSAGES_SUCCESS";
export const GET_GUEST_BOOK_MESSAGES_FAIL = "GET_GUEST_BOOK_MESSAGES_FAIL";
export const ADD_GUEST_BOOK_MESSAGE_START = "ADD_GUEST_BOOK_MESSAGE_START";
export const ADD_GUEST_BOOK_MESSAGE_SUCCESS = "ADD_GUEST_BOOK_MESSAGE_SUCCESS";
export const ADD_GUEST_BOOK_MESSAGE_FAIL = "ADD_GUEST_BOOK_MESSAGE_FAIL";
export const RESET_ADD_GUEST_BOOK_MESSAGE_SUCCESS =
  "RESET_ADD_GUEST_BOOK_MESSAGE_SUCCESS";
export const DELETE_GUEST_BOOK_MESSAGE_SUCCESS =
  "DELETE_GUEST_BOOK_MESSAGE_SUCCESS";
export const CLEAR_GUEST_BOOK_ERROR = "CLEAR_GUEST_BOOK_ERROR";
export const RESET_GUEST_BOOK = "RESET_GUEST_BOOK";
